[package]
name = "brightness-tray"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
monitor = { path = "monitor" }
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5", features = [] }
uuid = { version = "1.6", features = ["v4"] }
windows-version = "0.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
