import * as app from '@tauri-apps/api/app';
import { invoke } from "@tauri-apps/api/tauri";

const isDev = false;
const uuid = await invoke("uuid4");
console.log(await invoke("windows_version"));
const isWin11 = (await invoke("windows_version"))[3] >= 22000;

export default {
    isDev,
    userClosedIntro: false,
    theme: "default",
    icon: "icon",
    updateInterval: 500,
    openAtLogin: true,
    brightnessAtStartup: true,
    killWhenIdle: false,
    remaps: {},
    hotkeys: {},
    hotkeyPercent: 10,
    adjustmentTimes: [],
    adjustmentTimeIndividualDisplays: false,
    adjustmentTimeSpeed: "normal",
    adjustmentTimeAnimate: false,
    checkTimeAtStartup: true,
    order: [],
    monitorFeatures: {},
    hideDisplays: {},
    checkForUpdates: !isDev,
    dismissedUpdate: '',
    language: "system",
    settingsVer: "v" + await app.getVersion(),
    names: {},
    analytics: !isDev,
    scrollShortcut: true,
    useAcrylic: false,
    useNativeAnimation: false,
    sleepAction: "ps",
    hotkeysBreakLinkedLevels: true,
    enableSunValley: true,
    isWin11,
    windowsStyle: "system",
    hideClosedLid: false,
    getDDCBrightnessUpdates: false,
    detectIdleTimeEnabled: false,
    detectIdleTimeSeconds: 0,
    detectIdleTimeMinutes: 5,
    overrideTaskbarPosition: false,
    overrideTaskbarGap: false,
    disableWMIC: false,
    disableWMI: false,
    disableWin32: false,
    autoDisabledWMI: false,
    disableOverlay: false,
    disableMouseEvents: false,
    disableThrottling: false,
    userDDCBrightnessVCPs: {},
    forceLowPowerGPU: false,
    ddcPowerOffValue: 6,
    disableAutoRefresh: false,
    disableAutoApply: false,
    uuid,
    branch: "master"
  };
